export const PREZZI = {
  BIOSCAN: 300,
  TRATTAMENTO: 500,
  FITOTERAPIA: 150,
  MANTENIMENTO: 500,
  LETTURA_REFERTO: 0
} as const

export const DURATE_MINUTI = {
  BIOSCAN: 60,
  TRATTAMENTO: 60,
  FITOTERAPIA: 30,
  MANTENIMENTO: 60,
  LETTURA_REFERTO: 30
} as const
